name: Deploy on PROD

on:
  push:
    branches: [PROD]

jobs:
  deploy:
    name: Déploiement webhook sur Proxmox
    runs-on: ubuntu-latest

    steps:
      - name: Vérification du repo
        uses: actions/checkout@v4

      - name: Appel webhook Proxmox
        run: |
          curl -X POST https://kopo.systems/api/forum/deploy-prod \
               -H "X-Auth-Token: ${{ secrets.WEBHOOK_TOKEN_FRONT }}"
